### ISSUE TITLE
Save button does not appear on blog pages/posts

### ISSUE THREAD

**Issue by bantmen** [suryatech/Quora-Save-To-Pocket#10]

**Comment by cberkay** [comment]
I just realized that the error was more general than this and is related to #9

**Comment by suryatech** [comment]
Hi, this is also related to #9.

The idea is to extend the functionality for questions/answers to blog posts and pages.
The Quora website keeps changing its HTML layout and it is for this reason that the extension keeps breaking.

I will try to fix it soon.

**Comment by suryatech** [comment]
@cberkay Version 0.2.0 should fix this - https://chrome.google.com/webstore/detail/quora-save-to-pocket/lllehdhoocnpkkhpnoonnpcfcjmnmlil
I decided to fix this after a long time. Apologies for the delay.

Let me know if it works for you.

**Comment by bantmen** [comment]
@suryatech Just tested and it seems to work well :)
