### ISSUE TITLE
How is this supposed to work?

### ISSUE THREAD

**Issue by JMFrancia** [suryatech/Quora-Save-To-Pocket#14]
1. I log into Quora via Quora-Save-To-Pocket options
2. I open up a quora question page
3. I click on the Quora-Save-To-Pocket button on Chrome
4. It opens up a menu with 5 options: 
- Quora save to pocket
- Options
- Remove from Chrome
- Hide in Chrome Menu
- Manage Extensions
5. I click Quora Save to Pocket
6. I am redirected to the Quora Save To Pocket git page
7. Ok, go back, try clicking my regular save to pocket extension (thinking maybe they work together?)
8. Open up pocket, Quora only saved the question, and not any of the answers.  

What am I missing here?

**Comment by suryatech** [comment]
Assuming you've given access to save items to your pocket account via the login page present in options, you should see 'Save to Pocket' links next to answers/questions.

For reference, look at the images here: https://chrome.google.com/webstore/detail/quora-save-to-pocket/lllehdhoocnpkkhpnoonnpcfcjmnmlil?hl=en

**Comment by JMFrancia** [comment]
Thank you! I didn't realize the extension would add a link to the page itself.
