### ISSUE TITLE
Different answer getting saved, not the one user is currently viewing

### ISSUE THREAD

**Issue by cprasad111** [suryatech/Quora-Save-To-Pocket#15]
Save to Pocket saves some different random answer to the question and not the one which the user is currently viewing. Unfortunately, this issue is with Quora app/website as well

https://www.quora.com/unanswered/Save-to-Pocket-option-selecting-from-Share-button-on-Quora-Android-app-does-not-save-the-correct-answer-link-Is-it-a-bug-What-is-the-other-way-to-save-answer-to-Pocket-correctly-Refer-link-for-details?srid=dp19

https://photos.google.com/share/AF1QipNWQd4mnsz8xVPshX6T8K1U6Tn8bisGjCFwAQSKIotKSSZ1_QSVyw4WS_6DY8LJEA?key=T3N1YWlyUjhTRXg1ZDZNd0p6aUtGbWZjMnVqZklR

**Comment by boatwreck** [comment]
This extension doesn't work on mobile devices. Please get in touch with Pocket's team for resolution.

If you are facing this issue with the save to pocket google chrome extension, please share either the relevant screenshots or the steps to reproduce this issue.

**Comment by suryatech** [comment]
This extension doesn't work on mobile devices. Please get in touch with Pocket's team for resolution.

If you are facing this issue with the save to pocket google chrome extension, please share either the relevant screenshots or the steps to reproduce this issue.

**Comment by cprasad111** [comment]
This happens in the Chrome as well. As I mentioned, even the Quora own Share button in the browser has this bug. The link that gets copied is not of the answer in display/currently being read, but some random answer of the same question

**Answer I Saved to Pocket**

![image](https://user-images.githubusercontent.com/4571514/34411147-d7b58ada-ec0f-11e7-8f63-358fdc2f7a25.png)


**In Pocket - another answer for the same question**

![image](https://user-images.githubusercontent.com/4571514/34411172-f91564f2-ec0f-11e7-9f1f-2cbaaaefb860.png)

**Comment by suryatech** [comment]
It seems like Quora changed certain aspects of the html behind each answer.
Thank you for the bug report, I'll take a look at this.

**Comment by suryatech** [comment]
@cprasad111 I've pushed the fix (v0.2.2) to the chrome web store.
Let me know if it works for you.

**Comment by cprasad111** [comment]
It's works now. Great

I would like to inform that the same issue I raised to Pocket Team as well, and they had marked it as  bug. The email they sent is below, if you would want to have a quick read.

I'll by replying to them mentioning about your Chrome Extension and that you have resolved the same issue for your Chrome extension. They may follow suite for their app

![image](https://user-images.githubusercontent.com/4571514/34458848-15c8020e-ee1c-11e7-9b8d-d22e44fd0d1a.png)
