### ISSUE TITLE
Doesn't seem working with new Quora interface on 3/5/2018

### ISSUE THREAD

**Issue by yxliang01** [suryatech/Quora-Save-To-Pocket#17]
I can't see any "save to Pocket" like text in quora answers. The screenshots are showing the old Quora interfaces.

Thanks

**Comment by suryatech** [comment]
Looks like the HTML layout has changed again. I'll try to fix this soon. Thank you for informing 👍

**Comment by rd1** [comment]
hi, i just installed this extension, and indeed save to pocket doesn't show up on the pages. if you're looking for a new project for chrome and Quora related, how about "Print from Quora" ?

**Comment by yxliang01** [comment]
@rd1 Err how is the new project related to this issue? 😂

**Comment by rd1** [comment]
its obviously not, ever heard of a "suggestion" before?

**Comment by yxliang01** [comment]
@rd1 Sure. But, I don't see such suggestion would fit in this context.

**Comment by magicspeller** [comment]
Ever since I installed this extension, long ago, I have never been able to find a "Save to Pocket" link. I am currently running Windows 10 and the latest version of Chrome.

Does it work for anybody? If so, what am I doing wrong?

**Comment by suryatech** [comment]
This project is now deprecated. If anyone wants to maintain, shoot me an email.
