### ISSUE TITLE
Save question details while saving answers to Pocket

### ISSUE THREAD

**Issue by suryatech** [suryatech/Quora-Save-To-Pocket#2]
_Requested by Piyush Patil_

When saving an answer, it would be great if the question details could also be saved.

**Comment by suryatech** [comment]
Thanks for requesting this.

As of now, when I save an answer to Pocket, the corresponding title in Pocket is
**XYZ's answer to Question Q**

What other information would you like to have while saving to Pocket?

**Comment by abhinavm24** [comment]
![t](https://cloud.githubusercontent.com/assets/4698976/9981486/234656b8-5fdc-11e5-9e5c-6daf01525fd9.JPG)

hopefully that helps

**Comment by suryatech** [comment]
Added a save to pocket link next to the question with v0.2.0
It's up to Pocket to pull relevant info.

Extension cannot control what information is sent to pocket to be saved.
