### ISSUE TITLE
Add to Pocket not working for Quora Reading List

### ISSUE THREAD

**Issue by abhinavm24** [suryatech/Quora-Save-To-Pocket#7]
None of the answers on page https://www.quora.com/reading_list/all  have save to pocket button.

**Comment by suryatech** [comment]
@abhinavm24 
Thanks for reporting!

Can reproduce it at my end. Will look into it.

**Comment by abhinavm24** [comment]
Was that "can't reproduce it"?
On 05-Sep-2015 9:11 pm, "Surya P" <notifications@github.com> wrote:

> @abhinavm24 <https://github.com/abhinavm24>
> Thanks for reporting!
>
> Can reproduce it at my end. Will look into it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/suryatech/Quora-Save-To-Pocket/issues/7#issuecomment-137968339>
> .
>

-- 

------------------------------
*Disclaimer: *This email and any files transmitted with it are confidential 
and intended solely for the use of the individual or entity to whom they 
are addressed. If you have received this email in error please notify the 
system manager. This message contains confidential information and is 
intended only for the individual named. If you are not the named addressee 
you should not disseminate, distribute or copy this e-mail. Please notify 
the sender immediately by e-mail if you have received this e-mail by 
mistake and delete this e-mail from your system. If you are not the 
intended recipient you are notified that disclosing, copying, distributing 
or taking any action in reliance on the contents of this information is 
strictly prohibited.

**Comment by abhinavm24** [comment]
It would be great, if we could add all the answers on the reading list page in just one go.

**Comment by suryatech** [comment]
Will release a new version by EOD which contains the fix

Have a look at #4 for the save all feature

**Comment by suryatech** [comment]
@abhinavm24 Could you please confirm if this helps?

**Comment by abhinavm24** [comment]
yeah, works seamlessly.
Thankyou
