### ISSUE TITLE
" Save to Pocket" link appears only for the first couple of answers / questions on most Quora web pages.

### ISSUE THREAD

**Issue by sjie** [suryatech/Quora-Save-To-Pocket#9]
Hi Surya,

First of all, thanks a lot for this great extension. It's exactly what I need. 

It seems have a bug on my Chrome, for whatever page I browse on Quora, the "Save to Pocket" link appears only for the first couple of answers / questions on most Quora web pages. By "first couple of", the number can be 4, 5, 6, etc.

Appreciate if you have time to look at this issue and make this great extension greater.

Thanks!

**Comment by suryatech** [comment]
@sjie Sorry for the delay.
Thanks for reaching out. I will try to fix this soon.

**Comment by suryatech** [comment]
@sjie  Version 0.2.0 should fix this - https://chrome.google.com/webstore/detail/quora-save-to-pocket/lllehdhoocnpkkhpnoonnpcfcjmnmlil

Let me know if it works for you.

**Comment by Sashusss** [comment]
For me, "save to Pocket" link does not appear at all.

**Comment by suryatech** [comment]
@Sashusss I see you've opened a new ticket. Let's discuss over there.
